apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: test-client-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: test-client
  placement:
    clusterAffinity:
      clusterNames:
        - proxmox-member-2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - proxmox-member-2
            weight: 10
