apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: test-server-import-policy
spec:
  resourceSelectors:
    - apiVersion: multicluster.x-k8s.io/v1alpha1
      kind: ServiceImport
      name: test-server-import
  placement:
    clusterAffinity:
      clusterNames:
        - proxmox-member-2
