apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
  name: test-server-policy
spec:
  resourceSelectors:
    - apiVersion: apps/v1
      kind: Deployment
      name: test-server
    - apiVersion: v1
      kind: Service
      name: test-server
  placement:
    clusterAffinity:
      clusterNames:
        - proxmox-member-1
        - proxmox-member-2
    replicaScheduling:
      replicaDivisionPreference: Weighted
      replicaSchedulingType: Divided
      weightPreference:
        staticWeightList:
          - targetCluster:
              clusterNames:
                - proxmox-member-1
            weight: 10
          - targetCluster:
              clusterNames:
                - proxmox-member-2
            weight: 10
